### ISSUE TITLE
Correlation remover doesn't show up in plots when using compare_mitigation_methods()

### ISSUE THREAD

**Issue by jaared** [EqualityAI/EqualityML#12]
Correlation remover doesn't show up in plots when using compare_mitigation_methods()

Suggest we add it to the list here. 

https://github.com/EqualityAI/EqualityML/blob/90e04435007a653b5c4c69dc5a9b86e0c5d34ce7/equalityml/fair.py#L172-L182

**Comment by JoaoGranja** [comment]
Is correlation remover method a good option to mitigate bias when using the statistical parity ratio metric?

**Comment by jaared** [comment]
That is a very good question and I had to think about it. The answer is no. 

The correlation remover should help meet the **separation** fairness criteria. It should improve these fairness metrics for binary classification: 

* equal opportunity   
* predictive equality  
* equalized odds (both of the above) 

https://en.wikipedia.org/wiki/Fairness_(machine_learning)
