### ISSUE TITLE
Make results of compare_mitigation_models() reproducible

### ISSUE THREAD

**Issue by jaared** [EqualityAI/EqualityML#13]
Results are not reproducible. Add random_seed = ... to resampling method of bias mitigation, possibly other functions as well. 

https://github.com/EqualityAI/EqualityML/blob/90e04435007a653b5c4c69dc5a9b86e0c5d34ce7/equalityml/fair.py#L617-L625

**Comment by JoaoGranja** [comment]
Fixed
