### ISSUE TITLE
self.threshold may mean self._threshold? 

### ISSUE THREAD

**Issue by jaared** [EqualityAI/EqualityML#14]
I didn't notice self.threshold being declared. Possibly I missed it. I did see self._threshold. Is it declared someplace I missed? If not, possible typo. 

https://github.com/EqualityAI/EqualityML/blob/90e04435007a653b5c4c69dc5a9b86e0c5d34ce7/equalityml/fair.py#L704-L726

**Comment by JoaoGranja** [comment]
threshold is a property of FAIR class with specific setter and getter methods, while self._threshold is a private member of FAIR class.
