### ISSUE TITLE
Add random_seed for resampling

### ISSUE THREAD

**Issue by jaared** [EqualityAI/EqualityML#16]
Resampling is random so we need to make it reproducible. 

I think dalex.resample uses numpy. possibly we can just put np.random_seed(random_seed) in the code someplace. 

Let me know if we need to talk about this one. 

https://github.com/EqualityAI/EqualityML/blob/90e04435007a653b5c4c69dc5a9b86e0c5d34ce7/equalityml/fair.py#L270-L294

**Comment by JoaoGranja** [comment]
Fixed
